# Generated by Django 3.1.7 on 2021-04-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210405_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=10, unique=True)),
                ('Last_Name', models.CharField(max_length=10, unique=True)),
                ('Father_Name', models.CharField(max_length=10, unique=True)),
                ('Image', models.ImageField(upload_to='image/')),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.BooleanField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
