# Generated by Django 3.1.7 on 2021-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20210405_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
