# Generated by Django 3.1.7 on 2021-05-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='Batch',
        ),
    ]
