# Generated by Django 3.1.7 on 2021-05-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20210504_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='demo.student'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Abbreviation', models.CharField(max_length=10)),
                ('students', models.ManyToManyField(to='demo.Student')),
            ],
        ),
    ]
