# Generated by Django 3.1.7 on 2021-05-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20210504_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='Abbreviation',
            new_name='batch_abbreviation',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='name',
            new_name='batch_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Batch',
            new_name='batch',
        ),
    ]
