# Generated by Django 3.1.7 on 2021-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20210504_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Date_of_Birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Father_Name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_abbreviation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(related_name='batch', to='demo.Student'),
        ),
    ]
