# Generated by Django 3.1.7 on 2021-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20210519_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='batch',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='number',
            new_name='batch',
        ),
        migrations.AlterField(
            model_name='department',
            name='students',
            field=models.ManyToManyField(related_name='department', to='demo.Student'),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='batch',
            field=models.CharField(max_length=10),
        ),
    ]
